POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "ivan@hogwarts.uk",
    "password": "ravenclaw123"
}

###
POST http://localhost:3000/refresh_token
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWQzNWUzOGEyMDQzZTE0MDk3YTM3MDgiLCJlbWFpbCI6Iml2YW5AaG9nd2FydHMudWsiLCJ1c2VySUQiOiJkMzAyY2NiMjlhODcxOWQ3NTI3YzRlM2QzZTk0ZmIyZmNmYmFjNzZkOTQyNjVjZjdlNWE1MTY4MzM5ZWZkOWEzIiwibmFtZSI6Iml2YW4iLCJwYXNzd29yZCI6IiQyYSQxMCRDblhrRVBqU2NtT21vQlRSbUtTM2kudnguQmdYeUFzUDZEbm8xRVV2MjA3MUJEdXJBcncvdSIsImlzSG9zdCI6dHJ1ZSwiX192IjowLCJpYXQiOjE2NDEyNDIxNzQsImV4cCI6MTY0MTMyODU3NH0.4sA_LzIknjlxipy6cMbQ8_LTfBcQvrSgrZfQKpfE8NU

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "ivan@hogwarts.uk",
    "name": "ivan",
    "password": "ravenclaw123",
    "isHost": true
}

###
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "username": "ivan@hogwarts.uk"
}
